// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egzkpyprimmddwmvqpwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnemtweXByaW1tZGR3bXZxcHdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NjgxODYsImV4cCI6MjA2OTI0NDE4Nn0.0aM8q63ES3ODr4nJAM8tTpcmJ07MCV9DFdzoL223zGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});